# This workflow uses actions that are not certified by GitHub.
name: Test

on:
  push:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: awalsh128/cache-apt-pkgs-action@latest
    - uses: coursier/cache-action@v6
      with:
        packages: valgrind
        version: 1.0
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - Install sbt
      run: apt install -y sbt
    - name: Run tests
      run: sbt test
